BEGIN;

ALTER TABLE public.marketing_campaigns
  ADD COLUMN IF NOT EXISTS views integer NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS viewers integer NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS engagements integer NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS reach integer NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS page_likes integer NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS link_clicks integer NOT NULL DEFAULT 0;

ALTER TABLE public.marketing_social_metrics
  ADD COLUMN IF NOT EXISTS views integer NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS likes integer NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS reach integer NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS leads integer NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS engagements integer NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS clicks integer NOT NULL DEFAULT 0;

COMMIT;
